# Generated by Django 5.2.6 on 2025-09-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('organizer', models.TextField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
