# Generated by Django 5.2.6 on 2025-09-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
